# Generated by Django 2.1.7 on 2019-02-22 02:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('dcode', models.IntegerField()),
                ('dist_name', models.CharField(max_length=18)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('code1', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
